// <auto-generated />
namespace NetworkServer.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update0111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update0111));
        
        string IMigrationMetadata.Id
        {
            get { return "201701112144285_Update 01.11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
